Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using CPTWorkouts.Models;

namespace CPTWorkouts.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            var model = new AboutViewModel
            {
            };

            return View(model);
        }
    }
}

Controllers/ComprasController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CPTWorkouts.Data;
using CPTWorkouts.Models;
using Microsoft.AspNetCore.Authorization;

namespace CPTWorkouts.Controllers
{
    [Authorize(Roles = "Treinador")]
    public class ComprasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ComprasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Compras
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Compras
                .Include(c => c.Cliente)
                .Include(c => c.Servico);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Compras/Details/5
        public async Task<IActionResult> Details(int? clienteFK, int? servicoFK)
        {
            if (clienteFK == null || servicoFK == null)
            {
                return NotFound();
            }

            var compras = await _context.Compras
                .Include(c => c.Cliente)
                .Include(c => c.Servico)
                .FirstOrDefaultAsync(m => m.ClienteFK == clienteFK && m.ServicoFK == servicoFK);
            if (compras == null)
            {
                return NotFound();
            }

            return View(compras);
        }

        // GET: Compras/Create
        public IActionResult Create()
        {
            ViewData["ClienteFK"] = new SelectList(_context.Clientes, "Id", "Nome");
            ViewData["ServicoFK"] = new SelectList(_context.Servicos, "Id", "Nome");
            return View();
        }

        // POST: Compras/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DataCompra,ValorCompraAux,ServicoFK,ClienteFK")] Compras compras)
        {
            if (ModelState.IsValid)
            {
                compras.ValorCompra = Convert.ToDecimal(compras.ValorCompraAux.Replace('.', ',')); // Convert ValorCompraAux to decimal
                _context.Add(compras);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClienteFK"] = new SelectList(_context.Clientes, "Id", "Nome", compras.ClienteFK);
            ViewData["ServicoFK"] = new SelectList(_context.Servicos, "Id", "Nome", compras.ServicoFK);
            return View(compras);
        }

        // GET: Compras/Edit/5
        public async Task<IActionResult> Edit(int? clienteFK, int? servicoFK)
        {
            if (clienteFK == null || servicoFK == null)
            {
                return NotFound();
            }

            var compras = await _context.Compras
                .FirstOrDefaultAsync(c => c.ClienteFK == clienteFK && c.ServicoFK == servicoFK);

            if (compras == null)
            {
                return NotFound();
            }

            ViewData["ClienteFK"] = new SelectList(_context.Clientes, "Id", "Nome", compras.ClienteFK);
            ViewData["ServicoFK"] = new SelectList(_context.Servicos, "Id", "Nome", compras.ServicoFK);

            return View(compras);
        }

        // POST: Compras/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int clienteFK, int servicoFK, [Bind("DataCompra,ValorCompraAux,ServicoFK,ClienteFK")] Compras compras)
        {
            if (clienteFK != compras.ClienteFK || servicoFK != compras.ServicoFK)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    compras.ValorCompra = Convert.ToDecimal(compras.ValorCompraAux.Replace('.', ',')); // Convert ValorCompraAux to decimal
                    _context.Update(compras);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ComprasExists(clienteFK, servicoFK))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["ClienteFK"] = new SelectList(_context.Clientes, "Id", "Nome", compras.ClienteFK);
            ViewData["ServicoFK"] = new SelectList(_context.Servicos, "Id", "Nome", compras.ServicoFK);

            return View(compras);
        }

        // GET: Compras/Delete/5
        public async Task<IActionResult> Delete(int? clienteFK, int? servicoFK)
        {
            if (clienteFK == null || servicoFK == null)
            {
                return NotFound();
            }

            var compras = await _context.Compras
                .Include(c => c.Cliente)
                .Include(c => c.Servico)
                .FirstOrDefaultAsync(m => m.ClienteFK == clienteFK && m.ServicoFK == servicoFK);
            if (compras == null)
            {
                return NotFound();
            }

            return View(compras);
        }

        // POST: Compras/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int clienteFK, int servicoFK)
        {
            try
            {
                var compras = await _context.Compras
                    .FirstOrDefaultAsync(m => m.ClienteFK == clienteFK && m.ServicoFK == servicoFK);

                if (compras == null)
                {
                    return NotFound();
                }

                _context.Compras.Remove(compras);
                await _context.SaveChangesAsync();
            }
            catch (Exception ex)
            {
                // Log the exception or handle it as needed
                return RedirectToAction(nameof(Index)); // Redirect to index on error
            }

            return RedirectToAction(nameof(Index));
        }

        private bool ComprasExists(int clienteFK, int servicoFK)
        {
            return _context.Compras.Any(e => e.ClienteFK == clienteFK && e.ServicoFK == servicoFK);
        }
    }
}

Controllers/EquipasController.cs
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CPTWorkouts.Data;
using CPTWorkouts.Models;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;
using Microsoft.AspNetCore.Authorization;

namespace CPTWorkouts.Controllers
{
    [Authorize(Roles = "Treinador")]
    public class EquipasController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public EquipasController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Equipas
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Equipas.ToListAsync());
        }

        // GET: Equipas/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var equipa = await _context.Equipas
                .Include(e => e.ListaClientes)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (equipa == null)
            {
                return NotFound();
            }

            return View(equipa);
        }

        // GET: Equipas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Equipas/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm] Equipas equipa, [FromForm] IFormFile ImagemLogo)
        {
            // a anotação [Bind] informa o servidor de quais os atributos
            // que devem ser lidos do objeto que vem do browser

            /* Guardar a imagem no disco rígido do Servidor
             * Algoritmo
             * 1- há ficheiro?
             *    1.1 - não
             *          devolvo controlo ao browser
             *          com mensagem de erro
             *    1.2 - sim
             *          Será imagem (JPG,JPEG,PNG)?
             *          1.2.1 - não
             *                  uso logótipo pre-definido
             *          1.2.2 - sim
             *                  - determinar o nome da imagem
             *                  - guardar esse nome na BD
             *                  - guardar o ficheir no disco rígido
             */

            if (ModelState.IsValid)
            {
                try
                {
                    if (ImagemLogo == null || ImagemLogo.Length <= 0)
                    {
                        ModelState.AddModelError("ImagemLogo", "Deve fornecer um logotipo");
                        return BadRequest(ModelState);
                    }

                    if (!(ImagemLogo.ContentType == "image/png" || ImagemLogo.ContentType == "image/jpeg"))
                    {
                        ModelState.AddModelError("ImagemLogo", "O logotipo deve ser uma imagem PNG ou JPEG.");
                        return BadRequest(ModelState);
                    }

                    //gerar um nome de ficheiro
                    string nomeImagem = $"{Guid.NewGuid()}{Path.GetExtension(ImagemLogo.FileName)}";

                    // guardar a imagem no wwwroot/imagens
                    string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "Imagens", nomeImagem);

                    using (var stream = new FileStream(imagePath, FileMode.Create))
                    {
                        await ImagemLogo.CopyToAsync(stream);
                    }

                    // Redimensionar a imagem
                    ResizeImage(imagePath);

                    // gaurdar o objecto equipas na base de dados
                    equipa.Logotipo = nomeImagem;
                    _context.Add(equipa);
                    await _context.SaveChangesAsync();

                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", $"Erro ao guardar equipa: {ex.Message}");
                    return BadRequest(ModelState);
                }
            }

            return BadRequest(ModelState);
        }

        // redimensionar imagem
        private void ResizeImage(string imagePath)
        {
            using (var image = Image.Load(imagePath))
            {
                int novaLargura = 800;
                image.Mutate(x => x.Resize(novaLargura, 0));
                image.Save(imagePath);
            }
        }

        // GET: Equipas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var equipa = await _context.Equipas.FindAsync(id);
            if (equipa == null)
            {
                return NotFound();
            }

            return View(equipa);
        }

        // POST: Equipas/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Logotipo")] Equipas equipa)
        {
            if (id != equipa.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(equipa);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EquipasExists(equipa.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(equipa);
        }

        // GET: Equipas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var equipa = await _context.Equipas
                .FirstOrDefaultAsync(m => m.Id == id);

            if (equipa == null)
            {
                return NotFound();
            }

            return View(equipa);
        }

        // POST: Equipas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var equipa = await _context.Equipas.FindAsync(id);
            if (equipa != null)
            {
                _context.Equipas.Remove(equipa);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        private bool EquipasExists(int id)
        {
            return _context.Equipas.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CPTWorkouts</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CPTWorkouts.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-very-dark box-shadow mb-0">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CPTWorkouts</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="navbar-brand" asp-area="" asp-controller="About" asp-action="Index">Sobre</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Equipas" asp-action="Index">Equipas</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Servicos" asp-action="Index">Servicos</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Treinadores" asp-action="Index">Treinadores</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Compras" asp-action="Index">Compras</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Utilizadores" asp-action="Index">Utilizadores</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-0">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <!--&copy; 2024 - CPTWorkouts - <a asp-area="" asp-page="/Privacy">Privacy--!>
        </div>
    </footer>

    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    *@
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>