Models/Servicos.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace CPTWorkouts.Models
{
    public class Servicos
    {
        // Vamos usar a Entity Framework para a construção do Model
        // https://learn.microsoft.com/en-us/ef/

        public Servicos()
        {
            ListaTreinadores = new HashSet<Treinadores>();
            ListaCompras = new HashSet<Compras>();
        }
        /// <summary>
        /// chave primária do serviço
        /// </summary>
        [Key] // PK
        public int Id { get; set; }
        /// <summary>
        /// Nome do Serviço a ser prestado pelo treinador
        /// </summary>
        public string Nome { get; set; }
        /// <summary>
        /// Preco do serviço a ser prestado pelo treinador
        /// </summary>
        public decimal Preco { get; set; }

        /* ****************************************
         * Construção dos Relacionamentos
         * *************************************** */


        // relacionamento M-N, SEM atributos no relacionamento
        public ICollection<Treinadores> ListaTreinadores { get; set; }


        // relacionamento N-M, COM atributos no relacionamento
        public ICollection<Compras> ListaCompras { get; set; }
    }
}

Controllers/ServicosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CPTWorkouts.Data;
using CPTWorkouts.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace CPTWorkouts.Controllers
{
    [Authorize(Roles = "Treinador")]
    public class ServicosController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public ServicosController(
            ApplicationDbContext context,
            UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Servicos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Servicos.ToListAsync());
        }

        // GET: Servicos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var servicos = await _context.Servicos
                .Include(s => s.ListaTreinadores)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (servicos == null)
            {
                return NotFound();
            }

            return View(servicos);
        }


        // GET: Servicos/Create
        public IActionResult Create()
        {
            // obter a lista de Treinadores existentes na BD
            ViewData["ListaTreinadores"] = _context.Treinadores.OrderBy(p => p.Nome).ToList();
            return View();
        }

        // POST: Servicos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Preco")] Servicos servico, int[] listaIdsTreinadores)
        {
            // VALIDAR SE FOI ESCOLHIDO PELO MENOS UM Treinador

            // PQ HÁ Treinador(ES)
            var listaTreinadores = new List<Treinadores>();
            foreach (var treinadorId in listaIdsTreinadores)
            {
                //var treinador = _context.Treinadores.FirstOrDefault(t => t.Id == treinadorId);
                var treinador = await _context.Treinadores.FindAsync(treinadorId);
                if (treinador != null)
                {
                    listaTreinadores.Add(treinador);
                }
            }


            if (listaTreinadores != null)
            {
                servico.ListaTreinadores = listaTreinadores;
            }
            else
            {
                // se chego aqui, houve tratalhada feita no browser
                // gerar mensagem de erro
                // notificar utilizador
                // enviar controlo à VIEW
            }

            if (ModelState.IsValid)
            {

                _context.Add(servico);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            ViewData["ListaTreinadores"] = _context.Treinadores.ToList();
            return View(servico);
        }

        // GET: Servicos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

                if (User.IsInRole("Treinador"))
                {
                    var servico = await _context.Servicos.FindAsync(id);
                    if (servico == null)
                    {
                        return NotFound();
                    }

                    // falta fazer a lista de Treinadores, como no método da criação


                    return View(servico);
                }

                // se chego aqui é pq sou treinador
                // será que tenho autorização de editar o servico?

                // obter ID da pessoa autenticada
                var userId = _userManager.GetUserId(User);

                // ID do Utilizador autenticado
                var idTreinador = _context.Treinadores
                                   .Where(t => t.UserID == userId)
                                   .FirstOrDefault()
                                   .Id;

                // Investigar se o treinador está associado à UC
                var ServicosComTreinador = _context.Servicos
                                        .Where(servico => servico.Id == id &&
                                               servico.ListaTreinadores.Any(t => t.Id == idTreinador))
                                        .FirstOrDefault();

            // se a UC não é nula, é pq o treinador está associado à UC
            if (ServicosComTreinador != null)
                {
                // falta fazer a lista de treinadores, como no método da criação

                // enviar UC para a View
                return View(ServicosComTreinador);
                }
                else
                {
                // O treinador naão está associado
                // gerar Mensagem de erro
                // notificar utilizador
                // etc.

                return NotFound();
                }
            }

            // POST: Servicos/Edit/5
            // To protect from overposting attacks, enable the specific properties you want to bind to.
            // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
            [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Preco")] Servicos servicos)
        {
            if (id != servicos.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(servicos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ServicosExists(servicos.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(servicos);
        }

        // GET: Servicos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var servicos = await _context.Servicos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (servicos == null)
            {
                return NotFound();
            }

            return View(servicos);
        }

        // POST: Servicos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var servicos = await _context.Servicos.FindAsync(id);
            if (servicos != null)
            {
                _context.Servicos.Remove(servicos);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ServicosExists(int id)
        {
            return _context.Servicos.Any(e => e.Id == id);
        }
    }
}

Controllers/TreinadoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CPTWorkouts.Data;
using CPTWorkouts.Models;
using Microsoft.AspNetCore.Authorization;

namespace CPTWorkouts.Controllers
{
    [Authorize(Roles = "Treinador")]
    public class TreinadoresController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TreinadoresController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Treinadores
        public async Task<IActionResult> Index()
        {
            return View(await _context.Treinadores.ToListAsync());
        }

        // GET: Treinadores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var treinadores = await _context.Treinadores
                .FirstOrDefaultAsync(m => m.Id == id);
            if (treinadores == null)
            {
                return NotFound();
            }

            return View(treinadores);
        }
        // GET: Treinadores/Create
        public IActionResult Create()
        {
            return View();
        }
        // POST: Treinadores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,DataNascimento,Telemovel,UserID")] Treinadores treinadores)
        {
            if (ModelState.IsValid)
            {
                _context.Add(treinadores);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(treinadores);
        }
        // GET: Treinadores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var treinadores = await _context.Treinadores.FindAsync(id);
            if (treinadores == null)
            {
                return NotFound();
            }
            return View(treinadores);
        }
        // POST: Treinadores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,DataNascimento,Telemovel,UserID")] Treinadores treinadores)
        {
            if (id != treinadores.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(treinadores);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TreinadoresExists(treinadores.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(treinadores);
        }
        // GET: Treinadores/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var treinadores = await _context.Treinadores
                .FirstOrDefaultAsync(m => m.Id == id);
            if (treinadores == null)
            {
                return NotFound();
            }

            return View(treinadores);
        }
        // POST: Treinadores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var treinadores = await _context.Treinadores.FindAsync(id);
            if (treinadores != null)
            {
                _context.Treinadores.Remove(treinadores);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TreinadoresExists(int id)
        {
            return _context.Treinadores.Any(e => e.Id == id);
        }
    }
}

Views/Servicos/Create.cshtml
@model CPTWorkouts.Models.Servicos

@{
    ViewData["Title"] = "Create";
}

<h1>Criar</h1>

<h4>Servicos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>

            @* listar os Treinadores*@
            <div class="form-group">
                <label class="control-label">Lista Treinadores</label>
                @foreach (var treinador in (List<Treinadores>)ViewData["ListaTreinadores"] ?? Enumerable.Empty<Treinadores>())
                {
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="@treinador.Id" name="listaIdsTreinadores">
                        <label class="form-check-label">
                            @treinador.Nome
                        </label>
                    </div>
                }
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retornar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Servicos/Delete.cshtml
@model CPTWorkouts.Models.Servicos

@{
    ViewData["Title"] = "Delete";
}

<h1>Apagar</h1>

<h3>Tem a certeza que pretende apagar?</h3>
<div>
    <h4>Servicos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Preco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Preco)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Apagar" class="btn btn-danger" /> |
        <a asp-action="Index">Retornar</a>
    </form>
</div>

Views/Servicos/Details.cshtml
@model CPTWorkouts.Models.Servicos

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Servicos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Preco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Preco)
        </dd>
        <dt class="col-sm-2">
            Treinadores
        </dt>
        <dd class="col-sm-10">
            <ul>
                @foreach (var treinador in Model.ListaTreinadores ?? Enumerable.Empty<Treinadores>())
                {
                    <li>
                        <a asp-action="Details"
                           asp-controller="Treinadores"
                           asp-route-id="@Model.Id">
                            @treinador.Nome
                        </a>
                    </li>
                }
            </ul>
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Editar</a> |
    <a asp-action="Index">Retornar</a>
</div>

Views/Servicos/Edit.cshtml
@model CPTWorkouts.Models.Servicos

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>Servicos</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retornar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Servicos/Index.cshtml
@model IEnumerable<CPTWorkouts.Models.Servicos>

@{
    ViewData["Title"] = "Index";
}

<h1>Servicos</h1>

<p>
    <a asp-action="Create">Criar um novo Servico</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Preco)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Preco)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Detalhes</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Apagar</a>
            </td>
        </tr>
}
    </tbody>
</table>